test13

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -59,7 +59,7 @@ jobs:
                 docker images
 
                 echo 'Running Docker container...'
-                docker run -dp 3000:5173 nepalgames:latest || echo 'Failed to start container'
+                docker run -dp 5173:5173 nepalgames:latest || echo 'Failed to start container'
 
                 echo 'Docker containers:'
                 docker ps -a
